### ISSUE TITLE
Stuck at loading screen on fresh install

### ISSUE THREAD

**Issue by tennekey** [linuxserver/docker-organizr#17]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu Server 16.04

Here are the parameters I have set in docker-compose.yml:
```
organizr:
    container_name: organizr
    image: lsiocommunity/organizr
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - web
    volumes:
      - /opt/app/organizr:/config
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:app.domain.com"
```

Docker logs are empty. Chrome console output shows "Need Setup = Yes | Config Ready = No", but no errors. 

Check.php shows everything green.

I did check the container's nginx logs, and noticed a few errors, like:
```
FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream
```
