### ISSUE TITLE
Homepage not persistent

### ISSUE THREAD

**Issue by tahahawa** [linuxserver/docker-organizr#33]
If using the homepage, and you set it up, it doesn't persist in the config directory.

If the container is stopped or restarted, the homepage settings get reset, but not the tabs.

I'd have to do a bit of digging if I were to make a PR to fix this, haven't yet looked at how the container is built

**Comment by CHBMB** [comment]
@tahahawa Might be helpful if you provided us with the info in the template.  I suspect it's how you're deploying it seeing as your is the only report we've had of this.

**Comment by tahahawa** [comment]
I appreciate the reply, here's the details on the container config: https://gist.github.com/tahahawa/01782c860efb19426074280362021588

**Comment by raph521** [comment]
Phew, I thought it was just me - I actually have this same issue

**Comment by CHBMB** [comment]
@Raph521 @tahahawa Can you post your docker run command/compose file please?

@tahahawa Whilst I'm sure all the details are there in what you posted, easy to read it is not.

**Comment by raph521** [comment]
Sure!  Here's the relevant bits of my docker-compose file.  I'm running it on a Raspberry Pi 3B:

```
version: '2.1'

services:
    organizr:
        container_name: organizr
        image: linuxserver/organizr:latest
        restart: unless-stopped
        volumes:
            - /media/pi/FANTOM/rpi/anarky/organizr/config:/config
        environment:
            - TZ=America/New_York
            - PGID=1000
            - PUID=1000
        ports:
            - 8080:80
```

All other config persists across container re-creation except for the homepage definition

**Comment by CHBMB** [comment]
@Raph521 Can you tell me what you're defining as your homepage?

**Comment by raph521** [comment]
I have Plex, Sonarr, Radarr, and Transmission on my homepage

**Comment by raph521** [comment]
I did some digging within the container, and think the homepage configuration is being stored in the following location:

/var/www/html/config/config.php

I suppose I could mount that directory as a volume?

**Comment by CHBMB** [comment]
I'm a bit confused now as `/var/www/html/config/config.php` is a symlink to `/config/organizr/config.php` so it's already in persistent storage.
```
root@870114678a13:/config/organizr# ls -la /var/www/html/config/
total 16
drwxrwxr-x 1 abc abc   74 Jun 12 08:49 .
drwxr-xr-x 1 abc abc  724 Jun 11 04:01 ..
-rw-rw-r-- 1 abc abc   30 Mar  1 21:27 .htaccess
lrwxrwxrwx 1 abc abc   27 Jun 12 08:49 config.php -> /config/organizr/config.php
-rw-rw-r-- 1 abc abc 5621 Mar  1 21:27 configDefaults.php
```

**Comment by raph521** [comment]
Within my container, that's not a symlink...

```
root@6bcc7243f820:/var/www/html/config# ls -lah
total 252K
drwxrwxr-x 1 abc users 4.0K Jun 12 18:45 .
drwxr-xr-x 1 abc users 4.0K Jun 10 23:01 ..
-rw-rw-r-- 1 abc users   30 Mar  1 16:27 .htaccess
-rw-r--r-- 1 abc users 221K Jun 12 18:44 cacert.pem
-rw-r--r-- 1 abc users 1.1K Jun 12 18:44 config.bak.php
-rw-r--r-- 1 abc users 1.1K Jun 12 18:45 config.php
-rw-rw-r-- 1 abc users 5.5K Mar  1 16:27 configDefaults.php
root@6bcc7243f820:/var/www/html/config# ls -lah /config/organizr
total 1.5M
drwx------ 1 abc users 4.0K Jun 12 18:56  .
drwx------ 1 abc users 4.0K Apr  9 19:23  ..
drwx------ 1 abc users    0 May  4 18:31  backups
-rw------- 1 abc users  174 Apr  9 19:23  config.php
-rw------- 1 abc users  988 Apr  8 21:14  index.html
-rw------- 1 abc users  932 Jun 12 18:40  loginLog.json
-rw------- 1 abc users 368K Jun 12 18:56  org.log
-rw------- 1 abc users 489K Apr  9 22:47 'org[2019-04-09].log'
-rw------- 1 abc users 489K Apr 11 02:33 'org[2019-04-11].log'
-rw------- 1 abc users  12K Apr 14 13:43  speedtest.db
drwx------ 1 abc users    0 Apr  8 21:16  users
-rw------- 1 abc users  56K Jun 12 18:56  users.db
```

**Comment by raph521** [comment]
I eventually got this sorted by manually moving config.php to the proper location and creating the symlink within the container.

After that, whenever I destroyed/recreated the container, the symlink always exists and points to the right location.

**Comment by modelrockettier** [comment]
So I just ran into this issue today.  After a bit of investigation, it looks like when you click the save button in the organizr UI, rather than write to the file directly as you'd expect, it backs up the existing config.php and creates a new one.

E.g. on my system:
```
## Fresh organizr instance
$ docker exec organizr ls -l /var/www/html/config/
/var/www/html/config/:
total 8
lrwxrwxrwx 1 abc abc   27 Oct 12 16:34 config.php -> /config/organizr/config.php
-rw-rw-r-- 1 abc abc 5621 Mar  1  2019 configDefaults.php

## Change something minor in the advanced settings, then click save
$ docker exec organizr ls -l /var/www/html/config/

/var/www/html/config/:
total 12
lrwxrwxrwx 1 abc abc   27 Oct 12 16:34 config.bak.php -> /config/organizr/config.php
-rw-r--r-- 1 abc abc  379 Oct 12 16:34 config.php
-rw-rw-r-- 1 abc abc 5621 Mar  1  2019 configDefaults.php
```

So then end result is that the config.php symlink is now named config.bak.php after the save and the new settings are in a new file that will be blown away when the container is recreated.

In the meantime, you can work around it by just copying the new config.php into your config folder after making changes, e.g.
`docker exec organizr cp -v /var/www/html/config/config.php /config/organizr/config.php`

**Comment by lbesnard** [comment]
uploaded icons aren't persistent either

**Comment by romancin** [comment]
> uploaded icons aren't persistent either

Same problem here. I lost all my icons :(

**Comment by lbesnard** [comment]
@romancin my work around was to set up a small apache server in a container, and put the icons in that. then in organizr linking the icons adequatly
see https://www.tecmint.com/install-apache-web-server-in-a-docker-container/
and
```yaml
  tecmint-web:                                                                                                                                                                                                                                                                  
    container_name: web-server                                                                                                                                                                                                                                                  
    image: httpd:2.4                                                                                                                                                                                                                                                            
    ports:                                                                                                                                                                                                                                                                      
      - 9090:80                                                                                                                                                                                                                                                                 
    volumes:                                                                                                                                                                                                                                                                    
      - $DOCKER_CONFIG_PATH/howto:/usr/local/apache2/htdocs/                                                                                                                                                                                                                    
    restart: unless-stopped      
```
